### PR TITLE
Add support for French

### PR DESCRIPTION
**Pull request by Guid75**
Hi,

Here is my modest contribution to your great game. Tested on chromium/linux.

I added the french language at the end of every list but maybe you may want to sort them alphabetically one day.

Guillaume

### CODE REVIEW

**Comment by mxgrn** [comment]
Thanks a bunch Guillaume! It's live :)

**Comment by Guid75** [comment]
My pleasure. And thanks for this game, my kids and I love it.

**Comment by mxgrn** [comment]
Hey @Guid75 , if you still happen to be enjoying the game, would greatly appreciate your help with updating the French translations for the newest "2.0" version, which introduces a redesign, a chat, random player selection, and the "local" play (to play with someone on the same device). Cheers.

**Comment by Guid75** [comment]
Do you have a special request regarding https://en.wikipedia.org/wiki/T%E2%80%93V_distinction ?
For the phrase "Unload your mind while improving your memory", I could use the familiar form (often used in video games to establish a closer relationship with the player) or the more polite but distant form.
Please let me know.

**Comment by Guid75** [comment]
Well, finally I think I'll stick with the "distant" form since I was already using it in my previous translation work, if it's ok for you.

Sorry for the noise.

**Comment by mxgrn** [comment]
@Guid75 Whichever form you find appropriate as a native! In the Russian version I'm being rather informal, but I'm never sure it's the best. Would need A/B testing to make sure :)

Thanks!

**Pull request merged**
