### PR TITLE
Add support to PT (portuguese) language

### PR DESCRIPTION
**Pull request by tiagobarreto**

### CODE REVIEW

**Comment by tiagobarreto** [comment]
I think it's done.

**Comment by mxgrn** [comment]
Had to also modify `web/static/elm/I18n.elm` to make Elm pick up the translations. Updated the README accordingly. Thanks for your changes, they are now online!

**Comment by mxgrn** [comment]
Hey @tiagobarreto , if you still happen to be enjoying the game, would greatly appreciate your help with updating translations for the newest "2.0" version, which introduces a redesign, a chat, random player selection, and the "local" play (to play with someone on the same device). Cheers.

**Comment by tiagobarreto** [comment]
Yes, sure. You can rely on me.

**Pull request merged**
