### PR TITLE
Add supprot for zh-hans (Chinese Simplified)

### PR DESCRIPTION
**Pull request by Daniel-Xu**
Thanks for the great oss project. @mxgrn

### CODE REVIEW

**Comment by mxgrn** [comment]
Awesome work @Daniel-Xu, it's live now! Does the automatic language detection work fine in case of Chinese? That is, if you come to http://pairs.one - do you get redirect to http://pairs.one/zh-hans ? I tried to change my Chrome language settings to Simplified Chinese, but I keep coming to the English page instead.

**Comment by Daniel-Xu** [comment]
it doesn't work for me either, I will debug a bit tonight.

**Comment by mxgrn** [comment]
I'm not sure about the "-hans" part in the language format. I guess, if we leave only "zh", it will work. But I guess it'll show simplified Chinese also to, say, Taiwanese? Not sure still how it works.

**Comment by mxgrn** [comment]
Hey @Daniel-Xu , if you still happen to be enjoying the game, would greatly appreciate your help with updating translations for the newest "2.0" version, which introduces a redesign, a chat, random player selection, and the "local" play (to play with someone on the same device). Cheers.

**Pull request merged**
